### ISSUE TITLE
支持动态更新 apollo openapi 配置

### ISSUE THREAD

**Issue by fengjx** [fengjx/Sentinel#5]
在 sentinel-dashboard 运行时可以动态修改 apollo 配置，不需要重启服务

**Comment by yuebaix** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/89335097/198529124-291ff6c3-e642-4adb-89f4-903fa85f8c85.png">

这边应该把SYSTEM改为AUTHORITY，规则类型有bug～感谢大佬开源代码

**Comment by fengjx** [comment]
> <img alt="image" width="953" src="https://user-images.githubusercontent.com/89335097/198529124-291ff6c3-e642-4adb-89f4-903fa85f8c85.png">
> 
> 这边应该把SYSTEM改为AUTHORITY，规则类型有bug～感谢大佬开源代码

感谢反馈  #6
